export const SET_FORMA = 'SET_FORMA';
export const SET_MEDIDAS = 'SET_MEDIDAS';
export const SET_GENERO = 'SET_GENEROYCOLOR';
export const SET_COLOR = 'SET_COLOR';
export const SET_TACHA = 'SET_TACHA';
export const SET_TIPO_TACHA='SET_TIPO_TACHA';
export const SET_MODELO= 'SET_MODELO';
export const REFRESH_RESPALDO_PROPERTIES="REFRESH_RESPALDO_PROPERTIES";


export const ADD_TO_BASKET ="ADD_TO_BASKET";
export const REMOVE_FROM_BASKET="REMOVE_FROM_BASKET";
export const GET_TOTAL_PRICE="GET_TOTAL_PRICE";
export const ON_AMOUNT_CHANGED="ON_AMOUNT_CHANGED";
export const ON_LOADING="ON_LOADING";
export const CREATE_ORDER="CREATE_ORDER";
export const FORMA_DE_PAGO="FORMA_DE_PAGO";
export const FORMA_DE_ENVIO="FORMA_DE_ENVIO";
export const PROVINCIA_SELECTED="PROVINCIA_SELECTED";

export const SHOW_INFO_BASKET="SHOW_INFO_BASKET";
export const HIDE_INFO_BASKET="HIDE_INFO_BASKET";
export const UNMOUNT_CARRITO="UNMOUNT_CARRITO";

export const DISPLAY_TACHA_OPTIONS="DISPLAY_TACHA_OPTIONS";

export const AUTH_START="AUTH_START";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAIL="AUTH_FAIL";
export const AUTH_LOGOUT ="AUTH_LOGOUT";
